apiVersion: v1
kind: Secret
metadata:
  name: default-certificate
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV4akNDQXk2Z0F3SUJBZ0lSQVAzMExpSzROQlN2T0h6MjBwK0k4NTB3RFFZSktvWklodmNOQVFFTEJRQXcKZ2E4eEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEZDTUVBR0ExVUVDd3c1Y0dGMApjbWxqYTIxdmNtVmhkVUJRWVhSeWFXTnJjeTFOWVdOQ2IyOXJMVkJ5Ynk1c2IyTmhiQ0FvVUdGMGNtbGpheUJOCmIzSmxZWFVwTVVrd1J3WURWUVFEREVCdGEyTmxjblFnY0dGMGNtbGphMjF2Y21WaGRVQlFZWFJ5YVdOcmN5MU4KWVdOQ2IyOXJMVkJ5Ynk1c2IyTmhiQ0FvVUdGMGNtbGpheUJOYjNKbFlYVXBNQjRYRFRJek1ERXhNREExTURBMQpNRm9YRFRJMU1EUXhNREEwTURBMU1Gb3diVEVuTUNVR0ExVUVDaE1lYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwCklHTmxjblJwWm1sallYUmxNVUl3UUFZRFZRUUxERGx3WVhSeWFXTnJiVzl5WldGMVFGQmhkSEpwWTJ0ekxVMWgKWTBKdmIyc3RVSEp2TG14dlkyRnNJQ2hRWVhSeWFXTnJJRTF2Y21WaGRTa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGdDcjNqd1Q1RVlWRCsrSFV0K0FRRUpDWWh0VnFvbGYydnRvNGhqSm1EClF1ejBldHpEMERIWWI2a3hhckJLUXNrOFB2ODVYMWp1T3RJbVk1U0ZOWEJLM1NRZ0RCaWZOVFVCWkQ4SGJ2YysKc3A4SnVOaU5rVm1BM0JCT081YW8wemIvbFFlZE1kajRpWXdHSStzYXZBRHpZM1Y4S2RzOHEybm9HSmN6ZUxuRgpaVnRPc2ljQkl2NXpDRzZRQkx2ZWVRdXFQZXFsQ2tMR042ZzNiV3ZDYW5UQ3NCQnVPRzk5Vno0bTltR3g4R3JxCjM2c2U4SitjdjA3NElrQ1dTM3NHT1l5RzRmejU5NHRxQldLMEVycTVUTVJHOFVFYXA1ZEpYeTl2aGZ3N3dNcE4KOFNralkrYWpEK2p2emNibUVTOW5pZ053ZFdWdnRoSFJxKzdydUtHdjNFV0ZBZ01CQUFHamdaMHdnWm93RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1COEdBMVVkSXdRWU1CYUFGTWpBCjJmOXRqcXJIamVnK1BJMkF5RlYzeTlHRk1GSUdBMVVkRVFSTE1FbUNFREV5Tnk0d0xqQXVNUzV1YVhBdWFXK0MKRWlvdU1USTNMakF1TUM0eExtNXBjQzVwYjRJSmJHOWpZV3hvYjNOMGh3Ui9BQUFCaHhBQUFBQUFBQUFBQUFBQQpBQUFBQUFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQmdRQjJGbjNaTFl5aE1NaHliLzBrWmNtWEtlNzQzQ0t6CndOZlM5RHNkaldCcWg0eXJtQnZzbVpxK3d5dzloRDlKMWhKUCsyempYRDloN1l4VnBNSDRZbjZTaklBK3RuNEsKcjA2dUU5RlI0Q3gzMWx5WDlVanpMUnRaNEFqRlhid2liMVNPSStJbmE4Ykp1RlBoWUovWFR1UFNoTDZRMk5adApTTWRMS0d1b3VSVWhqWDR5VVZ1R3NyZ0IvWHNZYS9KRUp2dERCTVlHYTFKbUhqR0thQ25PYTF4anlCbnQwaVgwClc2dFR1RDhxQTVRS1V4SDJzaXVNSXFtakxDZ1luR01aeUpBamxYZVZZRlF3Rms3akRhTXBhRWRhclVBcUdTd3gKTXhKa1BHaGpOb2RGdUtmL1FCSlNJSjBLQVVzb2tJSVBxZkFVc1h3YldwYUE1ZTZhV2xEWHJST3ZNOXBCQTRsaQpncnV1NjFlOUx1d0hveHZGVG5KUVZ6S3lDOTRNdEF1ZWFQaW1FRVhWaFZydHFnMVphdWdkR1J0c2xwRzdjUW1kCkd0SklJbVh2NVRXNEpBZTVLRGIxZkhzeXk4Q2luRHdNbGJaT1huZWwyVXlVOVdOVUt4REEvZFN4emNLNWZiUXAKSG94OGpVcXoyQVZPN3hPUFF1VllrUFhpM1piMUtoODNQNlU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGdDcjNqd1Q1RVlWRCsKK0hVdCtBUUVKQ1lodFZxb2xmMnZ0bzRoakptRFF1ejBldHpEMERIWWI2a3hhckJLUXNrOFB2ODVYMWp1T3RJbQpZNVNGTlhCSzNTUWdEQmlmTlRVQlpEOEhidmMrc3A4SnVOaU5rVm1BM0JCT081YW8wemIvbFFlZE1kajRpWXdHCkkrc2F2QUR6WTNWOEtkczhxMm5vR0pjemVMbkZaVnRPc2ljQkl2NXpDRzZRQkx2ZWVRdXFQZXFsQ2tMR042ZzMKYld2Q2FuVENzQkJ1T0c5OVZ6NG05bUd4OEdycTM2c2U4SitjdjA3NElrQ1dTM3NHT1l5RzRmejU5NHRxQldLMApFcnE1VE1SRzhVRWFwNWRKWHk5dmhmdzd3TXBOOFNralkrYWpEK2p2emNibUVTOW5pZ053ZFdWdnRoSFJxKzdyCnVLR3YzRVdGQWdNQkFBRUNnZ0VBZWN2ZEoyL3FsZW9CeWxyditTbVhwVml4a2lteE8yMHZHTk01dVd0aUdVWE0KNDZ2WFVHeGliTE5uVzRJUWpJNTZMOUpmbGFVTUI1YmFvQndLcGRCRFY2K1k4QU1qYjRuUll3eElaNVlmdTJvSApvNVZseExCNzQ5Mit6NGo5Z3BJd21BbEF0bWhlOTk1dXpQZkIzQ3JRcVlBc1ltK3V5L0MwQm9VM3piZVg1b01MCkZ3MlUwZC95RHBXYTVaUHZNTXF6bHVjeXNEKzJSRmNjMklYZlM1QnVBT1BMWmFmS2V6ZmZMMm1DL3A4OXpmaFUKUEdoR04wMU11OUcxOGYrZ2JWMVdmZzNjOFozVnJGMmhVZlJxRm9GV3BhSXEzMnB0WnROcXlOTDYzeWp0dEgzSwpxVW1LYTQvVnFxZVNwZ1NsN0FWbmpLNUh4Wk4ySk5oaWc3N1prMnQ2RVFLQmdRRHVEbVhxcGY4WkZSQ2QxeVZsCjFTdE5GMUhvR1ZJdTZzamJKU3pXNE1aQTFidE81N2N0NXJWUlhtMjliMXNlK3VEVFN0WGdiVGd5TkJiWlpMa3MKcXNMdHVDMFlkdHlHb1owSlFOSGh1Nk5ZOGlyNnpJWXR3YUdSVDQ1ckhiMDdIWEtQMUEyNnBZb09ydDZncTNJSQo0b0kxY1ozSlZFaUIwdEE4UlFhbjlFUnkvd0tCZ1FEdzdldUZrSHFVcEphU2lCUHRhWXVRaE1MWFBJVG1WSkZ0CkRId0ZLZlQwZTloNDZnTjdrU2VjNHlTd3U2QkYxZWxpMkhneDlBbFc3akRQMElkMEFGNTZndW15cGtQZGlQT1cKN2w2Q0s3V3UvdkpjUUpWK053NitRWTJaYjllYmdtSHJ4cFZZL2RLa0R1THN3MitjMElvQnFGaVpIbnJtaUtlOAo2VEZ2THNmN2V3S0JnUUNrMUs5WTArdFlNSys2dXJlWVZRdVFhMjg1S0I4eGdUdm1FVTJFMDBveXBrcjFqWmZXClhvSjVmc3E1ZWhzN3pqWlIxdVZVYWd1Wkoxd1MxcDBwQW12S01kWjN0QVZwNndsUzJPRDZUZlFDcUZ0K0lKTmYKcDB6NTBuNG9TUVUzbzJJcG1JaVJEZ0lUdkoxRjNyQXMycm1SeThPWEhaYSszWHQxMzgyR0NhcERmUUtCZ0NseApNMmNKSUJ5N1p1OFRteUhtV3N4a0djTytORG9PWitsekVVNHVGbVdMZkFQb2RPcm5ZQUg3akU4ZUp3WjhNaVgvCmlFVkhiZWZYRnV4WU9VUjUzOGFCQ0VQamw1N2V0TS9NZHRNN1E0Z3pjR3J2N1FjRjMzSllna3ZYVWlYOHVtMDgKL21tTlY1TkN3RVBycGlJNk9OTHFLenREWSs2TnFSUzBvLzAwOWM5TEFvR0JBTHloYTZ2OGZKQ1lkTUg2bFd4Twpjc2h2V2JmK2RXTkdGVTBZc3huU2VsR1FFKzZlckxiZ01JZ1lxbmFob3YxYzh5T2lQdjh0WWk0L2dLcGhhbnAzCmFRSUtEeFBRS3pkUG5BaFZlbEQyRnA2ZGUzUnR5SGpyOGtaT3UzSTRNNE5yN0tvT2FxamgrM3R1ZDhWUWJhWFQKUVdwbDVPZ2UrMDVmMno0ME0vd1MwdkY2Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: default-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.127.0.0.1.nip.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.mysql.address=:3306"
    entryPoints:
     mysql:
       address: ':3306'
